spring.application.name=heimdall

spring.datasource.url=jdbc:postgresql://localhost:5432/heimdall
spring.datasource.username=postgres
spring.datasource.password=yourpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.grpc.server.port=9090
spring.grpc.server.reflection.enabled=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.jpa.hibernate.ddl-auto=update